[tox]
requires =
    tox>=4.2
env_list =
    ruff
    py{312, 313, 314}-django52-cms{50, 51}
    py{312, 313, 314}-django60-cms{50, 51}
skip_missing_interpreters=True
labels =
    compile = compile-py312, compile-py313, compile-py314

[testenv]
deps =
    -r tests/requirements/{envname}.txt
commands =
    {env:COMMAND:coverage} run -m pytest

[testenv:compile-py{312, 313, 314}]
description = Recompile pinned requirements for this Python version
skip_install = true
deps = pip-tools
commands = python {toxinidir}/tests/requirements/compile.py {posargs}

[testenv:ruff]
deps = ruff
commands = ruff check djangocms_file
skip_install = true
