# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 14:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_file', '0002_auto_20151202_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='cmsplugin_ptr',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='+', serialize=False, to='cms.CMSPlugin'),
        ),
    ]
