# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 13:41
from __future__ import unicode_literals

import cms.models.pluginmodel
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_file', '0003_rename_file_field_20160115_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='source',
            field=models.FileField(upload_to=cms.models.pluginmodel.get_plugin_media_path, verbose_name='source'),
        ),
    ]
